name: Banking System Project Automation
on:
  issues:
    types: [opened, closed, labeled, unlabeled]
  pull_request:
    types: [opened, closed, merged, ready_for_review, converted_to_draft]

jobs:
  manage-project-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Add to Project
        uses: actions/add-to-project@v0.5.0
        with:
          # Replace YOUR-PROJECT-NUMBER with actual number from project URL
          project-url: https://github.com/users/locemarn/projects/3
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update Project Status
        uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/users/locemarn/projects/YOUR-PROJECT-NUMBER
          github-token: ${{ secrets.GITHUB_TOKEN }}
          item-id: ${{ steps.add-to-project.outputs.itemId }}
          field-keys: Status
          field-values: |
            ${{ 
              github.event_name == 'pull_request' && github.event.action == 'opened' && 'In Progress' ||
              github.event_name == 'pull_request' && github.event.action == 'ready_for_review' && 'In Review' ||
              github.event_name == 'issues' && github.event.action == 'closed' && 'Done' ||
              contains(github.event.issue.labels.*.name, 'phase-1') && 'Phase 1 - Foundation' ||
              contains(github.event.issue.labels.*.name, 'phase-2') && 'Phase 2 - Enhanced' ||
              contains(github.event.issue.labels.*.name, 'phase-3') && 'Phase 3 - Modular' ||
              contains(github.event.issue.labels.*.name, 'phase-4') && 'Phase 4 - Production' ||
              'Backlog'
            }}
